name: Hourly Run
on: 
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  hourly-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the PowerShell runner script
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        id: powershell-runner-script
        run: |
          pwsh -File ./runner.ps1
