name: Hourly Run
on: 
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  daily-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the PowerShell runner script
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          pwsh -File ./runner.ps1
      - name: Push new data.json into master repo
        run: |
          git config --global user.name 'Gavin Eke'
          git config --global user.email 'GavinEke@users.noreply.github.com'
          git commit -am "data.json update"
          git push
